# Generated by Django 2.0.1 on 2018-02-12 01:18

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import webclient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='unknown', max_length=100, unique=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('green', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('blue', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('width', models.PositiveSmallIntegerField(default=1920)),
                ('height', models.PositiveSmallIntegerField(default=1080)),
                ('categoryType', models.ManyToManyField(to='webclient.CategoryType')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('contrast', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('saturation', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelShapes', models.TextField(max_length=10000)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('timeTaken', models.PositiveIntegerField(default=None, null=True)),
                ('categoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webclient.CategoryType')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='unknown', max_length=200, unique=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImageWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='imagewindow',
            unique_together={('x', 'y', 'width', 'height')},
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='imageWindow',
            field=models.ForeignKey(default=webclient.models.getDefaultImageWindowId, on_delete=django.db.models.deletion.CASCADE, to='webclient.ImageWindow'),
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='labeler',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.Labeler'),
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='parentImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webclient.Image'),
        ),
        migrations.AddField(
            model_name='imagefilter',
            name='imageLabel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.ImageLabel'),
        ),
        migrations.AddField(
            model_name='imagefilter',
            name='labeler',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.Labeler'),
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webclient.ImageSourceType'),
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('red', 'green', 'blue')},
        ),
        migrations.AddField(
            model_name='categorytype',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.Color'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('name', 'path')},
        ),
    ]
