# Generated by Django 2.0.1 on 2018-02-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='label_type',
            field=models.CharField(choices=[('R', 'Rectangle'), ('C', 'Circle')], default='C', max_length=1),
        ),
    ]
