# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelabel',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='timeTaken',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
