# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0002_image_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelShapes', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
        migrations.DeleteModel(
            name='ImageType',
        ),
        migrations.AddField(
            model_name='imagelabels',
            name='parentImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webclient.Image'),
        ),
    ]
