# Generated by Django 2.0.1 on 2018-01-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0002_auto_20160818_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField(default=0)),
                ('green', models.PositiveSmallIntegerField(default=0)),
                ('blue', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('red', 'green', 'blue')},
        ),
    ]
