# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0002_auto_20161208_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload',
            field=models.FileField(null=True, upload_to='image_uploads/'),
        ),
    ]
