# Generated by Django 2.0.1 on 2018-04-02 21:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0003_auto_20180216_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiledCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiledLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('northeast_Lat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('northeast_Lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('southwest_Lat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('southwest_Lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('zoom_level', models.PositiveSmallIntegerField(default=23)),
                ('label_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('label_type', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.TiledCategory')),
            ],
        ),
    ]
