# Generated by Django 2.0.1 on 2018-01-29 00:57

from django.db import migrations, models
import django.db.models.deletion
import webclient.models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0003_auto_20180129_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='color',
            field=models.ForeignKey(default=webclient.models.get_default_Color, on_delete=django.db.models.deletion.CASCADE, to='webclient.Color'),
        ),
    ]
