# Generated by Django 2.0.1 on 2018-01-29 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0004_categorytype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='blue',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='color',
            name='green',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='color',
            name='red',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)]),
        ),
    ]
