# Generated by Django 2.0.1 on 2018-04-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0004_tiledcategory_tiledlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='label_type',
            field=models.CharField(choices=[('R', 'Rectangle'), ('C', 'Circle'), ('P', 'Polygon'), ('A', 'Any')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='tiledlabel',
            name='category',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.CategoryType'),
        ),
        migrations.DeleteModel(
            name='TiledCategory',
        ),
    ]
