# Generated by Django 2.0.1 on 2018-02-12 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0005_auto_20180129_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.Color'),
        ),
    ]
