# Generated by Django 2.0.1 on 2018-04-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0005_auto_20180403_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytype',
            old_name='category',
            new_name='category_name',
        ),
    ]
