# Generated by Django 2.0.1 on 2018-01-29 02:07

from django.db import migrations, models
import django.db.models.deletion
import webclient.models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0005_auto_20180129_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='color',
            field=models.ForeignKey(default=webclient.models.get_color, on_delete=django.db.models.deletion.CASCADE, to='webclient.Color'),
        ),
    ]
