# Generated by Django 2.0.1 on 2018-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0006_auto_20180403_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiledlabel',
            name='label_type',
            field=models.CharField(choices=[('R', 'Rectangle'), ('C', 'Circle'), ('P', 'Polygon'), ('A', 'Any')], default='R', max_length=1),
        ),
    ]
