# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '1001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='categoryTypes',
            field=models.ManyToManyField(to='webclient.CategoryType'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='category_name',
            field=models.CharField(default='unknown', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='imagesourcetype',
            name='description',
            field=models.CharField(default='unknown', max_length=200, unique=True),
        ),
    ]
