# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '1002_auto_20160531_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('name', 'path')]),
        ),
    ]
