# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '1003_auto_20160531_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='categoryTypes',
            new_name='categoryType',
        ),
    ]
