# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '1005_imagefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefilter',
            name='imageLabel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webclient.ImageLabel'),
        ),
    ]
