# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webclient', '1006_imagefilter_imagelabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='imagefilter',
            name='imageLabel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.ImageLabel'),
        ),
        migrations.AddField(
            model_name='imagefilter',
            name='labeler',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.Labeler'),
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='labeler',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.Labeler'),
        ),
    ]
