# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import webclient.models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '1008_imagelabel_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('length', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='imagewindow',
            unique_together=set([('x', 'y', 'length', 'width')]),
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='ImageWindow',
            field=models.ForeignKey(default=webclient.models.getDefaultImageWindowId, on_delete=django.db.models.deletion.CASCADE, to='webclient.ImageWindow'),
        ),
    ]
