# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import webclient.models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '1009_auto_20160718_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelabel',
            name='ImageWindow',
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='imageWindow',
            field=models.ForeignKey(default=webclient.models.getDefaultImageWindowId, on_delete=django.db.models.deletion.CASCADE, to='webclient.ImageWindow'),
        ),
    ]
