# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '1010_auto_20160719_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefilter',
            name='brightness',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='imagefilter',
            name='contrast',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='imagefilter',
            name='saturation',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
