# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '1012_auto_20160726_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='length',
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveSmallIntegerField(default=1080),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveSmallIntegerField(default=1920),
        ),
    ]
